# os: windows

# version format
version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2019

environment:
  PYTHON_VERSION: 3.7

  # global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    # CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    - MINICONDA: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7.4"
      PYTHON_ARCH: "64"

init:
  -  cmd: ECHO %PYTHON_VERSION% %MINICONDA%
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmd: set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda info -a
  - cmd: conda config --add channels conda-forge anaconda
  - cmd: conda install -c conda-forge setuptools wheel conda-build anaconda-client conda-verify cython -y
  - cmd: conda install -c anaconda numpy -y
#  - cmd: conda create -q -n pagral python=%PYTHON_VERSION% Cython numpy conda-build anaconda-client conda-verify
#  - conda activate pagral
#  - pip install ggplot

#  - cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
#  - cmd: python --version
#
#  # Upgrade to the latest version of pip to avoid it displaying warnings
#  # about it being out of date.
#  - cmd: python -m pip install --upgrade pip
#  - cmd: pip install wheel setuptools Cython numpy

build: off

build_script:
  # Build the Cython extension
  - cmd: ECHO test text here!
  - cmd: python setup.py build_ext --inplace

# test_script:
  # Run the project tests and store results in .xml log
  #  - ps: |
  #      # this produces nosetests.xml which is uploaded on_finish
  #      &$env:PYTHON\python setup.py nosetests --with-xunit
  #      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

after_test:
  # If tests are successful, create binary packages for the project.
  - cmd: python setup.py bdist_wheel
  # - "python setup.py bdist_wininst"
  # - "python setup.py bdist_msi"
  # - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Upload test results to AppVeyor
  #  - ps: |
  #    # this uploads nosetests.xml produced in test_script step
  #    $wc = New-Object 'System.Net.WebClient'
  #    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\nosetests.xml))