name: pagral
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - icc_rt=2019.0.0
  - intel-openmp=2020.0
  - llvmlite=0.31.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1f
  - pip=20.0.2
  - python=3.7.7
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2

