package:
  name: pagral
  version: "1.0"

source:
  path: C:\Users\t.mazza\Desktop\CSS-Bioinformatics\pagral_project

build:
  number: 0
#  entry_points:
#    - pyntacle = pyntacle.pyntacle:App
 
requirements:
  host:
    - numpy
    - cython
    - python=3.7

  build:
    - pip
    - python ==3.7
    - distlib
    - setuptools
    - numpy
    - cython

  run:
    - python ==3.7
    - pip
    - setuptools
    - numpy
    - cython
    - sphinx

test:
  imports:
    - pagral
#  commands:
#    - pyntacle -h
    
about:
  home: https://github.com/mazzalab/pagral
  summary: A PArallel python GRAph Library
  license: GPL3
#  license_file: LICENSE.txt
