package:
  name: pagral
  version: "1.0"

source:
  path: C:\projects\pagral

build:
  number: 1.0
#  entry_points:
#    - pyntacle = pyntacle.pyntacle:App
 
requirements:
  host:
    - numpy==1.19.1
    - cython
    - python==3.7

  build:
    - {{ compiler('c') }}
    - pip
    - python ==3.7
    - distlib
    - setuptools
    - numpy==1.19.1
    - cython

  run:
    - python ==3.7
    - pip
    - setuptools
    - numpy==1.19.1
    - cython

test:
  imports:
    - pagral
#  commands:
#    - pyntacle -h
    
about:
  home: https://github.com/mazzalab/pagral
  summary: A PArallel python GRAph Library
  license: GPL3
#  license_file: LICENSE.txt
