{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: pagral
  version: {{ data.get('version') }}

#app:
#  icon: icon_64x64.png

source:
  git_url: https://github.com/mazzalab/pagral.git
  # path: C:\projects\pagral

build:
  number: 1.0
#  entry_points:
#    - pyntacle = pyntacle.pyntacle:App
 
requirements:
  host:
    - numpy==1.19.1
    - cython
    - python==3.7

  build:
    - {{ compiler('c') }}
    - pip
    - python ==3.7
    - distlib
    - setuptools
    - numpy==1.19.1
    - cython

  run:
    - python ==3.7
#    - pip
#    - setuptools
    - numpy==1.19.1
#    - cython

test:
  imports:
    - pagral
#  commands:
#    - pyntacle -h
    
about:
  home: https://github.com/mazzalab/pagral
  summary: A PArallel python GRAph Library
  license: GPL3
  dev_url: https://github.com/mazzalab/pagral
  doc_url: https://pypi.python.org/pypi/pagral
  doc_source_url: https://github.com/mazzalab/pagral/blob/master/README.rst
#  license_file: LICENSE.txt
